<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $report['title'] }} — Print</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #212529; }
        .print-header { border-bottom: 2px solid #212529; padding-bottom: 10px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th, td { border: 1px solid #dee2e6; padding: 6px 10px; text-align: left; }
        th { background: #f8f9fa; font-weight: 600; }
        .section-title { font-weight: 700; font-size: 14px; margin-top: 24px; margin-bottom: 8px; }
        .summary-grid { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 20px; }
        .summary-card { border: 1px solid #dee2e6; border-radius: 6px; padding: 10px 16px; min-width: 140px; }
        .summary-value { font-size: 18px; font-weight: 700; }
        .summary-label { font-size: 11px; color: #6c757d; }
        footer { border-top: 1px solid #dee2e6; padding-top: 8px; margin-top: 24px; font-size: 11px; color: #6c757d; }
        @media print {
            .no-print { display: none !important; }
            body { margin: 0; }
        }
    </style>
</head>
<body>

{{-- Print button (hidden when printing) --}}
<div class="no-print mb-3 p-3">
    <button onclick="window.print()" class="btn btn-primary btn-sm">
        <i class="bi bi-printer me-1"></i>Print / Save as PDF
    </button>
    <a href="{{ route('reports.show', [$type, 'from' => $from, 'to' => $to]) }}" class="btn btn-outline-secondary btn-sm ms-2">
        &larr; Back to Report
    </a>
</div>

<div class="container-fluid px-4">

    {{-- Header --}}
    <div class="print-header d-flex justify-content-between align-items-start">
        <div>
            <h1 class="h4 mb-1">{{ $report['title'] }}</h1>
            @if ($society)
                <div class="text-muted">{{ $society->name }}</div>
            @endif
            @if ($type !== 'occupancy')
                <div class="small text-muted">Period: {{ $from }} to {{ $to }}</div>
            @endif
        </div>
        <div class="text-end small text-muted">
            Generated: {{ now()->format('d M Y, h:i A') }}<br>
            CommunityOS
        </div>
    </div>

    {{-- Summary --}}
    @if (!empty($report['summary']))
    <div class="summary-grid">
        @foreach ($report['summary'] as $stat)
        <div class="summary-card">
            <div class="summary-value">{{ $stat['value'] }}</div>
            <div class="summary-label">{{ $stat['label'] }}</div>
        </div>
        @endforeach
    </div>
    @endif

    {{-- Main table --}}
    @if (!empty($report['columns']) && !empty($report['rows']))
    <div class="section-title">{{ $report['title'] }}</div>
    <table>
        <thead>
            <tr>
                @foreach ($report['columns'] as $col)
                    <th>{{ $col }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($report['rows'] as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($report['columns']) }}" style="text-align:center;color:#6c757d;">
                        No data for the selected period.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- Extra sections --}}
    @foreach ($report['extras'] ?? [] as $extra)
        @if (!empty($extra['columns']) && !empty($extra['rows']))
        <div class="section-title">{{ $extra['title'] }}</div>
        <table>
            <thead>
                <tr>
                    @foreach ($extra['columns'] as $col)
                        <th>{{ $col }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @forelse ($extra['rows'] as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ count($extra['columns']) }}" style="text-align:center;color:#6c757d;">No data.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
        @endif
    @endforeach

    <footer>
        Generated by CommunityOS &nbsp;·&nbsp; {{ now()->format('d M Y H:i:s') }}
        @if ($society) &nbsp;·&nbsp; {{ $society->name }} @endif
    </footer>

</div>

{{-- Auto-print on load (can be suppressed by adding ?noprint=1) --}}
@if (!request()->has('noprint'))
<script>window.addEventListener('load', function() { window.print(); });</script>
@endif

</body>
</html>
